### ISSUE TITLE
The 'await' operator can only be used within an async method

### ISSUE THREAD

**Issue by LLukens** [olsh/curl-to-csharp#11]
Im receiving the following C# error after converting a curl command as below.    It seems await is not properly used with SendAsync()?    Any ideas on what can modify/try on the response would be greatly appreciated.   Thank you!

**CURL INPUT:**

curl -k -X POST "https://localhost:31843/dsvc/v1/wwt/pyscript/score" \
-H 'Authorization: Bearer ****'
-H 'Cache-Control: no-cache' \
-H 'Content-Type: application/json' \
-d '{"relativeScriptPath": "scripts/scoring.py"}'

**C# OUTPUT:**

var handler = new HttpClientHandler();
handler.ServerCertificateCustomValidationCallback = (requestMessage, certificate, chain, policyErrors) => true; 

using (var httpClient = new HttpClient(handler))
{
    using (var request = new HttpRequestMessage(new HttpMethod("POST"), "https://localhost:31843/dsvc/v1/wwt/pyscript/score"))
    {
        request.Headers.TryAddWithoutValidation("Authorization", "Bearer ****");
        request.Headers.TryAddWithoutValidation("Cache-Control", "no-cache"); 
        request.Content = new StringContent("{\"relativeScriptPath\": \"scripts/scoring.py\"}");
        request.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json"); 

        var response = await httpClient.SendAsync(request);
    }
}

error CS4033: The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task'.

**Comment by anox** [comment]
Same Error with the GET Example

`using (var httpClient = new HttpClient())
{
    using (var request = new HttpRequestMessage(new HttpMethod("GET"), "https://github.com/"))
    {
        var response = await httpClient.SendAsync(request);
    }
}`

**Comment by olsh** [comment]
The `System.Net.Http.Client` class doesn't have an asynchronous version of `SendAsync` method, so you should use asynchronous one.
As the error suggested, you may only use the `await` operator in an `async` method, the best way is to rewrite your code with async/await. Please read about async/await operators
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/

If you want to use `async` in _a synchronous method_, you may use `Result` property on `SendAsync` method.
**NB** this may lead to deadlocks, please read more about async/await concept before using it!
https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

```csharp
using (var httpClient = new HttpClient())
{
    using (var request = new HttpRequestMessage(new HttpMethod("GET"), "https://github.com/"))
    {
        var response = httpClient.SendAsync(request).Result;
    }
}
```

**Comment by olsh** [comment]
Closed due to inactivity. Feel free to reopen the issue if you still have questions.
