### ISSUE TITLE
response.Content.ReadAsStringAsync()

### ISSUE THREAD

**Issue by TDroogers** [olsh/curl-to-csharp#138]
Thanks, this tool saved me a lot of time and having to think myself!

However, the only thing missing from the response was `var result = await response.Content.ReadAsStringAsync()`

**Comment by olsh** [comment]
Hi @TDroogers 

Glad to hear that the tool is useful.

> However, the only thing missing from the response was var result = await response.Content.ReadAsStringAsync()

There are many options for response handling. The ReadAsStringAsync method is not universal.
The response may not have content at all. Or you may want to read stream/bytes/headers. It's up to the developer how to handle the response.

**Comment by TDroogers** [comment]
Oke, thanks
