### ISSUE TITLE
Parameter "--compressed" is not supported

### ISSUE THREAD

**Issue by neelabh2010** [olsh/curl-to-csharp#14]
While I am converting my curl to C# statement its give me an error "Parameter "--compressed" is not supported".

**Comment by olsh** [comment]
Hey @neelabh2010,

Thanks for the feedback. 
I'm not sure how it should be implemented, do you know if HttpClient supports the feature?

**Comment by AdmiringWorm** [comment]
@olsh it is supported (*mostly*) by using the `HttpClientHandler` class, simple example using the basic `GET` example available on the website:

```cs
var handler = new HttpClientHandler();
handler.AutomaticDecompression = DecompressionMethods.All; // using System.Net

using (var httpClient = new HttpClient(handler))
{
    using (var request = new HttpRequestMessage(new HttpMethod("GET"), "https://github.com/"))
    {
        var response = await httpClient.SendAsync(request);
    }
}
```

There is no error reported if the compressions method isn't supported by HttpClient though, like the curl `--compression` flag do.

**Comment by olsh** [comment]
Hi @AdmiringWorm,

Thank you for the info! 🏅 
I've implemented this like in your example with one addition. `DecompressionMethods.All` was added in .NET Core 3.0, so I used `~DecompressionMethods.None` for backward compatibility with previous versions of .NET.

@neelabh2010 thank you for the suggestion 👍 

Please feel free to reopen the issue if something works not as expected.
