### ISSUE TITLE
Support for IP addresses and localhost in --proxy

### ISSUE THREAD

**Issue by alexyorke** [olsh/curl-to-csharp#16]
When I try to convert the following command,

```
curl https://example.com -x 123.0.4.3:1234
```

I get the following error:

```
Unable to parse proxy URI
```

When I try to convert a `curl` command which uses `localhost` as the proxy,

```
curl https://example.com -x localhost:1234
```

I get the following error:

```
Proxy scheme "localhost" is not supported
```

Given that `curl` can use IP addresses as proxies (with no protocol), I think that `curl-to-csharp` should support this usage of `curl`.

**Comment by olsh** [comment]
Hi @alexyorke,

Thanks for opening the issue. Please feel free to reopen if the fix didn't help.
