### ISSUE TITLE
Don't convert to code, but return an actual populated HttpRequestMessage.

### ISSUE THREAD

**Issue by frankhommers** [olsh/curl-to-csharp#166]
Hi there,

I would like to use this component to be able to configure a request fully in a configuration file, load it and run it from the same project.

So therefore instead of the ToCsharp function which returns code, I am thinking of ToHttpRequestMessage function, which actually returns that so I can fire the request directly from the CommandLineParsing code.

Is this feasible?

Thanks,

Frank

**Comment by olsh** [comment]
Hi @frankhommers 

Well, some curl options require configuration of `HttpClientHandler`, using `HttpRequestMessage` is not enough.

Probably this will be useful for you. In this code, we convert curl command to code, compile the generated code, execute it and read content of `HttpResponseMessage`.
https://github.com/olsh/curl-to-csharp/blob/4b61d1f79013f3ad414ed599dd6282b32bc73000/src/CurlToCSharp.IntegrationTests/RequestsTests.cs#L102-L125

**Comment by olsh** [comment]
The scripting API doesn't require an SDK. Please find more info here.
https://github.com/dotnet/roslyn/blob/main/docs/wiki/Scripting-API-Samples.md

I think that it's possible to return configured objects, but I don't have time to implement it. So, PR is welcome ;)

**Comment by frankhommers** [comment]
I don't have time either, and I have moved on to a different solution. So no problem ;-)
