### ISSUE TITLE
Add support for --upload-file

### ISSUE THREAD

**Issue by Krutonium** [olsh/curl-to-csharp#2]
This is a neat project. I look forward to using it in the future :)

Thanks!

**Comment by Krutonium** [comment]
BTW an example of this commands use: 
`curl --upload-file ./hello.txt https://transfer.sh/hello.txt `

**Comment by olsh** [comment]
@Krutonium 
Implemented, please give it a try and let me know if it works as expected.

**Comment by Krutonium** [comment]
Yep, worked perfectly, thanks!
