### ISSUE TITLE
Header parameters not added.

### ISSUE THREAD

**Issue by ranjan250** [olsh/curl-to-csharp#5]
curl -X GET \
'http://sample.com/packages \
-H 'authorization: BEARER 0f3146534535353534809e' \
-H 'content-type: application/x-www-form-urlencoded' \

this gives below C# code : 
`using (var httpClient = new HttpClient())
{
    using (var request = new HttpRequestMessage(new HttpMethod("POST"), "http://sample.com/packages \n-H"))
    {
        var response = await httpClient.SendAsync(request);
    }
}`

Cannot find Header authorization and content type.

**Comment by olsh** [comment]
Hi @ranjan250 ,

I suppose there is an issue with an extra comma before the URL parameter

Here is the correct syntax.
```
curl -X GET 
http://sample.com/packages 
-H 'authorization: BEARER 0f3146534535353534809e' 
-H 'content-type: application/x-www-form-urlencoded' \
```

Also, please note, that there is no sense to send `Content-Type` header since you don't send any data in the request body and the request verb is `GET`.

**Comment by olsh** [comment]
Closed due to inactivity.
Feel free to reopen the issue.
