### ISSUE TITLE
Fails on edge case of -X Get method, but with -d content

### ISSUE THREAD

**Issue by JoshKnightDatamine** [olsh/curl-to-csharp#51]
A third party had setup an API with commands like this
curl -X get -H "Content-Type: application/json" -H "Accept: application/json" -d @company.json https://apiurl....

which after mucking around found out .NET doesn't support your generated code. See
https://stackoverflow.com/questions/3981564/cannot-send-a-content-body-with-this-verb-type

**Comment by olsh** [comment]
Hi @JoshKnightDatamine,

Thank you for the feedback.

> which after mucking around found out .NET doesn't support your generated code. See
> https://stackoverflow.com/questions/3981564/cannot-send-a-content-body-with-this-verb-type

The converter generates code that uses HttpClient (not WebRequest as discussed in the SO thread that you sent). So it's theoretically should work (sadly, I can't test it right now)
https://stackoverflow.com/a/47902348

**Comment by olsh** [comment]
Closed due to inactivity
