### ISSUE TITLE
Incorrect use of HttpClient

### ISSUE THREAD

**Issue by Juka117** [olsh/curl-to-csharp#6]
Putting the HttpClient in a using in this case is not the best way to go. If you put your curl to C# output into a timer with 50ms delay it will break after 15 seconds or so.

Instead you should apply the practice in this article:
https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

Otherwise, super tool mind you. Thank you!

**Comment by olsh** [comment]
Hi @Juka117,

Thanks for the feedback. 👍 

I'm aware of the problem. 
The tool was created to produce a minimum piece of code which can be compiled or run with LinqPad or something. I can remove the using statement and leave a comment like `inject your singleton HttpClient here` but for some cases we need to modify HttpClient (for example with -x Proxy parameter).

If you have any suggestions on how I can improve the situation, please let me know.

**Comment by olsh** [comment]
Closed due to inactivity.
