### ISSUE TITLE
The command does not start with “curl” and successfully passed the verification

### ISSUE THREAD

**Issue by shaofing** [olsh/curl-to-csharp#81]
The command does not start with “curl” and successfully passed the verification

`--location --request POST 'http://localhost:5001/api/SCMBaseService/GetUdfButtons' \
--header 'Content-Type: application/json' \
--data-raw '{
    "v": {
        "SysId": "OMS",
        "ModelName": "Purchase"
    },
    "lg": "zh_cn",
    "tk": "09ff6d32-bfa0-45dd-ae75-51d136f48c04"
}'`

This command does not start with “curl” .

**Comment by olsh** [comment]
Hi @shaofing 
This is by design.
