### ISSUE TITLE
Not supported singleQuote  escape 

### ISSUE THREAD

**Issue by shaofing** [olsh/curl-to-csharp#82]
不支持curl 的单引号转义，curl 的转义符是'\''  
Not supported singleQuote  Escape 
![image](https://user-images.githubusercontent.com/21122388/163960101-5818e1d3-918e-4136-9381-55281b1e8e6f.png)
![image](https://user-images.githubusercontent.com/21122388/163960240-a761b9d5-f8a6-4ffd-8007-baf22a5f8ad2.png)

`curl --location --request POST 'http://localhost/test' \
--header 'Content-Type: application/json' \
--data-raw '{
    "tttt":"value1'\''hhh"
}'`

**Comment by shaofing** [comment]
![image](https://user-images.githubusercontent.com/21122388/163972055-7d7c6712-0501-4dac-b371-154fbef397e7.png)
`curl --location --request POST 'http://localhost/test' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsontxt":"{\"name\":\"name1\"}"
}'`

Not supported   `\"`

**Comment by shaofing** [comment]
@jiahao1553 CurlParser  的nuget包是你推上去吗？

**Comment by olsh** [comment]
Fixed 18b50544da6ec8e321f6106faf2633e555969b44
